Universidad Torcuato Di Tella

Licenciatura en Tecnología Digital\
**Tecnología Digital VI: Inteligencia Artificial**

# **Tensores de PyTorch**

Esta *notebook* tiene como objetivo brindar una **comprensión** fundamental de los **tensores** y explorar sus **operaciones** esenciales.

Pueden encontrar la documentación oficial [acá](https://pytorch.org/docs/stable/torch.html).

In [1]:
import torch

### **1. Creación de tensores**


In [2]:
# Tensor vacio.
shape = (2, 3)
empty_torch = torch.empty(shape)
print(f'Tensor vacío:\n{empty_torch}')

# Tensor con ceros.
zeros = torch.zeros(shape)
print(f'\nTensor con ceros:\n{zeros}')

# Tensor con unos.
ones = torch.ones(shape)
print(f'\nTensor con unos:\n{ones}')

# Tensor con valores aleatorios.
torch.manual_seed(912)
random = torch.randn(shape)
print(f'\nTensor con valores aleatorios:\n{random}')


Tensor vacío:
tensor([[4.7322e-41, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

Tensor con ceros:
tensor([[0., 0., 0.],
        [0., 0., 0.]])

Tensor con unos:
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Tensor con valores aleatorios:
tensor([[-0.7422,  0.2946,  0.2378],
        [ 0.6362,  1.3564, -1.1293]])


In [3]:
import numpy as np

# Tensores a partir de datos.
data = [[3.1415926, 2.71828], [1.61803, 0.0072897]]
tensor_data = torch.tensor(data)
print(f'Tensor a partir de {type(data)} queda:\n{tensor_data}')

# Tensor a partir de array.
np_array = np.array(data)
x_np = torch.tensor(np_array) #dtype = torch.float
print(f'\nTensor a partir de {type(np_array)} queda:\n{x_np}')

# Tensor a partir de otro tensor (toma las dimensiones del tensor para crear uno nuevo).
x_ones = torch.ones_like(tensor_data)
print(f'\nTensor a partir de {type(tensor_data)} queda:\n{x_ones}')

Tensor a partir de <class 'list'> queda:
tensor([[3.1416, 2.7183],
        [1.6180, 0.0073]])

Tensor a partir de <class 'numpy.ndarray'> queda:
tensor([[3.1416, 2.7183],
        [1.6180, 0.0073]], dtype=torch.float64)

Tensor a partir de <class 'torch.Tensor'> queda:
tensor([[1., 1.],
        [1., 1.]])


### **2. Atributos de un tensor**

In [4]:
torch.manual_seed(912)
tensor = torch.rand(3, 4)

print(f'Dimensiones: {tensor.shape}')
print(f'Tipo de dato: {tensor.dtype}')
print(f'Dispositivo en el cual está almacenado: {tensor.device}')

#paso el tensor a gpu
device = "cuda:0" if torch.cuda. is_available() else "cpu"
print(f'GPU disponible?: {device}')

tensor = tensor.to(device)
print(f'Dispositivo en el cual está almacenado: {tensor.device}')


Dimensiones: torch.Size([3, 4])
Tipo de dato: torch.float32
Dispositivo en el cual está almacenado: cpu
GPU disponible?: cpu
Dispositivo en el cual está almacenado: cpu


### **3. Operaciones con tensores**


In [5]:
print(tensor)

tensor([[0.5550, 0.6499, 0.1591, 0.1939],
        [0.0241, 0.9942, 0.9007, 0.1593],
        [0.9862, 0.9638, 0.8487, 0.0787]])


##### **3.a. Sumar todos los elementos**

In [6]:
sum = torch.sum(tensor)
print(f'Suma de todos los elementos: {sum.item()}')

Suma de todos los elementos: 6.51356315612793


##### **3.b. Media y desviación estándar**

In [7]:
mean = torch.mean(tensor)
std  = torch.std(tensor)
print(f'Media: {mean.item()}')
print(f'Desviación estándar: {std.item()}')

Media: 0.5427969098091125
Desviación estándar: 0.3944227993488312


##### **3.c. Multiplicación elemento a elemento**

In [8]:
y1 = tensor * tensor
y2 = tensor.mul(tensor)

print(y1)
print(y2)

tensor([[3.0801e-01, 4.2242e-01, 2.5320e-02, 3.7591e-02],
        [5.8236e-04, 9.8834e-01, 8.1134e-01, 2.5366e-02],
        [9.7257e-01, 9.2883e-01, 7.2024e-01, 6.1967e-03]])
tensor([[3.0801e-01, 4.2242e-01, 2.5320e-02, 3.7591e-02],
        [5.8236e-04, 9.8834e-01, 8.1134e-01, 2.5366e-02],
        [9.7257e-01, 9.2883e-01, 7.2024e-01, 6.1967e-03]])


##### **3.d. Multiplicación de matrices de tensores**

In [9]:
z1 = tensor @ tensor.T
z2 = tensor.matmul(tensor.T)

print(z1)
print(z2)

tensor([[0.7933, 0.8337, 1.3240],
        [0.8337, 1.8256, 1.7589],
        [1.3240, 1.7589, 2.6278]])
tensor([[0.7933, 0.8337, 1.3240],
        [0.8337, 1.8256, 1.7589],
        [1.3240, 1.7589, 2.6278]])


### **4. *Broadcasting* y operaciones de reducción**

##### **4.a. Broadcasting**

In [10]:
# Broadcasting.
A = torch.tensor([[1.0], [2.0], [3.0], [4.0], [5.0]])
B = torch.tensor([[10.0, 20.0, 30.0, 40.0, 50.0]])

result = A + B

print(f'Tensor A:\n{A}')
print(f'\nTensor B:\n{B}')
print(f'\nSuma elemento a elemento:\n{result}')


Tensor A:
tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.]])

Tensor B:
tensor([[10., 20., 30., 40., 50.]])

Suma elemento a elemento:
tensor([[11., 21., 31., 41., 51.],
        [12., 22., 32., 42., 52.],
        [13., 23., 33., 43., 53.],
        [14., 24., 34., 44., 54.],
        [15., 25., 35., 45., 55.]])


##### **4.b. Operaciones de reducción**

In [11]:
tensor = torch.tensor([[14, 11, 13, 21, 32],
                       [1, 2, 3, 4, 5],
                       [1., 1., 1., 1., 1.]])

sum_along_dim0 = torch.sum(tensor, dim = 0)
mean_along_dim1 = torch.mean(tensor, dim = 1)
max_value = torch.max(tensor)

print(tensor)
print(f'\nSumar sobre la dimensión 0: {sum_along_dim0}')
print(f'\nMedia de los valores de la dimensión 1: {mean_along_dim1}')
print(f'\nMáximo valor del tensor: {max_value.item()}')


tensor([[14., 11., 13., 21., 32.],
        [ 1.,  2.,  3.,  4.,  5.],
        [ 1.,  1.,  1.,  1.,  1.]])

Sumar sobre la dimensión 0: tensor([16., 14., 17., 26., 38.])

Media de los valores de la dimensión 1: tensor([18.2000,  3.0000,  1.0000])

Máximo valor del tensor: 32.0


### **5. *Indexing* y *reshaping***


##### **5.a. Indexing**

In [12]:
tensor = torch.rand(4, 4)
print(f'{tensor}')
print(f'\nPrimera fila: {tensor[0]}')
print(f'\nPrimera columna: {tensor[:, 0]}')
print(f'\nÚltima columna: {tensor[..., -1]}')

# Cambiamos la segunda columna.
tensor[:, 1] = 0
print(f'\nHabiendo modificado la segunda columna:\n{tensor}')

tensor([[0.4954, 0.6518, 0.5062, 0.0387],
        [0.9766, 0.2408, 0.7607, 0.2126],
        [0.6358, 0.5808, 0.1014, 0.5624],
        [0.1818, 0.4620, 0.7000, 0.6129]])

Primera fila: tensor([0.4954, 0.6518, 0.5062, 0.0387])

Primera columna: tensor([0.4954, 0.9766, 0.6358, 0.1818])

Última columna: tensor([0.0387, 0.2126, 0.5624, 0.6129])

Habiendo modificado la segunda columna:
tensor([[0.4954, 0.0000, 0.5062, 0.0387],
        [0.9766, 0.0000, 0.7607, 0.2126],
        [0.6358, 0.0000, 0.1014, 0.5624],
        [0.1818, 0.0000, 0.7000, 0.6129]])


##### **5.b. [*Reshape*](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html)**

In [13]:
tensor_a = torch.rand(10, 2)

# Convertir a dimensión (5, 4).
tensor_b = tensor_a.view(5, 4)

# Convertir a dimensión (2, 10).
tensor_c = tensor_a.view(2, 10) #(-1,10)

print(f'Tensor original con dimensión (10, 2):\n{tensor_a}')
print(f'\nTensor modificado a dimensión (5, 4):\n{tensor_b}')
print(f'\nTensor modificado a dimensión (2, 10):\n{tensor_c}')

Tensor original con dimensión (10, 2):
tensor([[0.8755, 0.6580],
        [0.7275, 0.0716],
        [0.5018, 0.1397],
        [0.2296, 0.3536],
        [0.9003, 0.4144],
        [0.9369, 0.2143],
        [0.8540, 0.2493],
        [0.8199, 0.5768],
        [0.5489, 0.5200],
        [0.8015, 0.0106]])

Tensor modificado a dimensión (5, 4):
tensor([[0.8755, 0.6580, 0.7275, 0.0716],
        [0.5018, 0.1397, 0.2296, 0.3536],
        [0.9003, 0.4144, 0.9369, 0.2143],
        [0.8540, 0.2493, 0.8199, 0.5768],
        [0.5489, 0.5200, 0.8015, 0.0106]])

Tensor modificado a dimensión (2, 10):
tensor([[0.8755, 0.6580, 0.7275, 0.0716, 0.5018, 0.1397, 0.2296, 0.3536, 0.9003,
         0.4144],
        [0.9369, 0.2143, 0.8540, 0.2493, 0.8199, 0.5768, 0.5489, 0.5200, 0.8015,
         0.0106]])


### **6. Concatenar y apilar**

In [14]:
tensor1 = torch.rand(3, 3)
tensor2 = torch.rand(3, 3)
tensor3 = torch.rand(3, 3)

print(f'Tensor 1:\n{tensor1}')
print(f'Tensor 2:\n{tensor2}')
print(f'Tensor 3:\n{tensor3}')

Tensor 1:
tensor([[0.7724, 0.8654, 0.8101],
        [0.9041, 0.4927, 0.2375],
        [0.5506, 0.2744, 0.3059]])
Tensor 2:
tensor([[0.8428, 0.7363, 0.9988],
        [0.9143, 0.1115, 0.9472],
        [0.7686, 0.2539, 0.8632]])
Tensor 3:
tensor([[0.5669, 0.5746, 0.5171],
        [0.2116, 0.6667, 0.9006],
        [0.7569, 0.5294, 0.6586]])


In [15]:
# Concatenamos sobre la primera dimensión (la número 0).
concatenated_tensor = torch.cat((tensor1, tensor2, tensor3), dim = 0)

print(concatenated_tensor)
print(concatenated_tensor.shape)

tensor([[0.7724, 0.8654, 0.8101],
        [0.9041, 0.4927, 0.2375],
        [0.5506, 0.2744, 0.3059],
        [0.8428, 0.7363, 0.9988],
        [0.9143, 0.1115, 0.9472],
        [0.7686, 0.2539, 0.8632],
        [0.5669, 0.5746, 0.5171],
        [0.2116, 0.6667, 0.9006],
        [0.7569, 0.5294, 0.6586]])
torch.Size([9, 3])


In [16]:
# Apilamos sobre la dimension 0.
stacked_tensor = torch.stack((tensor1, tensor2, tensor3), dim = 0)

print(stacked_tensor)
print(stacked_tensor.shape)

tensor([[[0.7724, 0.8654, 0.8101],
         [0.9041, 0.4927, 0.2375],
         [0.5506, 0.2744, 0.3059]],

        [[0.8428, 0.7363, 0.9988],
         [0.9143, 0.1115, 0.9472],
         [0.7686, 0.2539, 0.8632]],

        [[0.5669, 0.5746, 0.5171],
         [0.2116, 0.6667, 0.9006],
         [0.7569, 0.5294, 0.6586]]])
torch.Size([3, 3, 3])


### **7. Conversion entre PyTorch y NumPy**

In [17]:
pytorch_tensor = torch.rand(2, 3)
numpy_array = np.ones((2, 3))

# Convertimos un tensor de PyTorch a una matriz de NumPy.
converted_to_numpy = pytorch_tensor.numpy()
print(f'{converted_to_numpy} es de tipo {type(converted_to_numpy)}')

# Convertimos una matriz de NumPy a un tensor de PyTorch.
converted_to_pytorch = torch.from_numpy(numpy_array)
print(f'\n{converted_to_pytorch} es de tipo {type(converted_to_pytorch)}')

[[0.9924957  0.64196926 0.86930746]
 [0.29391897 0.13011676 0.27619123]] es de tipo <class 'numpy.ndarray'>

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64) es de tipo <class 'torch.Tensor'>


Es importante saber que estos objetos convertidos están utilizando la **misma memoria** subyacente que sus objetos fuente, lo que significa que los cambios en uno se reflejan en el otro. Veamos un ejemplo.

In [18]:
numpy_array[1, 1] = 23
print(converted_to_pytorch)

pytorch_tensor[1, 1] = 17
print(f'\n{converted_to_numpy}')

tensor([[ 1.,  1.,  1.],
        [ 1., 23.,  1.]], dtype=torch.float64)

[[ 0.9924957   0.64196926  0.86930746]
 [ 0.29391897 17.          0.27619123]]
