Universidad Torcuato Di Tella

Licenciatura en Tecnología Digital\
**Tecnología Digital VI: Inteligencia Artificial**

# **Tensores de PyTorch**

Esta *notebook* tiene como objetivo brindar una **comprensión** fundamental de los **tensores** y explorar sus **operaciones** esenciales.

Pueden encontrar la documentación oficial [acá](https://pytorch.org/docs/stable/torch.html).

In [2]:
import torch

### **1. Creación de tensores**


In [6]:
# Tensor vacio.
shape = (2, 3)
empty_torch = torch.empty(shape)
print(f'Tensor vacío:\n{empty_torch}')

# Tensor con ceros.
zeros = torch.zeros(shape)
print(f'\nTensor con ceros:\n{zeros}')

# Tensor con unos.
ones = torch.ones(shape)
print(f'\nTensor con unos:\n{ones}')

# Tensor con valores aleatorios.
torch.manual_seed(11)
random = torch.randn(shape)
print(f'\nTensor con valores aleatorios:\n{random}')


Tensor vacío:
tensor([[1.2414e-24, 1.4447e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

Tensor con ceros:
tensor([[0., 0., 0.],
        [0., 0., 0.]])

Tensor con unos:
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Tensor con valores aleatorios:
tensor([[ 0.7376,  1.9459, -0.6995],
        [-1.3023, -0.5133, -0.2696]])


In [15]:
import numpy as np

# Tensores a partir de datos.
data = [[3.1415926, 2.71828], [1.61803, 0.0072897]]
tensor_data = torch.tensor(data)
print(f'Tensor a partir de {type(data)} queda:\n{tensor_data}')

# Tensor a partir de array.
np_array = np.array(data)
x_np = torch.tensor(np_array) #dtype = torch.float
print(f'\nTensor a partir de {type(np_array)} queda:\n{x_np}')

# Tensor a partir de otro tensor (toma las dimensiones del tensor para crear uno nuevo).
x_ones = torch.ones_like(tensor_data)
print(f'\nTensor a partir de {type(tensor_data)} queda:\n{x_ones}')

Tensor a partir de <class 'list'> queda:
tensor([[3.1416, 2.7183],
        [1.6180, 0.0073]])

Tensor a partir de <class 'numpy.ndarray'> queda:
tensor([[3.1416, 2.7183],
        [1.6180, 0.0073]], dtype=torch.float64)

Tensor a partir de <class 'torch.Tensor'> queda:
tensor([[1., 1.],
        [1., 1.]])


### **2. Atributos de un tensor**

In [16]:
torch.manual_seed(11)
tensor = torch.rand(3, 4)

print(f'Dimensiones: {tensor.shape}')
print(f'Tipo de dato: {tensor.dtype}')
print(f'Dispositivo en el cual está almacenado: {tensor.device}')

#paso el tensor a gpu
device = "cuda:0" if torch.cuda. is_available() else "cpu"
print(f'GPU disponible?: {device}')

tensor = tensor.to(device)
print(f'Dispositivo en el cual está almacenado: {tensor.device}')


Dimensiones: torch.Size([3, 4])
Tipo de dato: torch.float32
Dispositivo en el cual está almacenado: cpu
GPU disponible?: cuda:0
Dispositivo en el cual está almacenado: cuda:0


### **3. Operaciones con tensores**


In [17]:
print(tensor)

tensor([[0.1490, 0.4866, 0.9857, 0.1684],
        [0.5839, 0.6936, 0.5831, 0.1284],
        [0.5721, 0.9248, 0.2693, 0.7825]], device='cuda:0')


##### **3.a. Sumar todos los elementos**

In [18]:
sum = torch.sum(tensor)
print(f'Suma de todos los elementos: {sum.item()}')

Suma de todos los elementos: 6.327479362487793


##### **3.b. Media y desviación estándar**

In [19]:
mean = torch.mean(tensor)
std  = torch.std(tensor)
print(f'Media: {mean.item()}')
print(f'Desviación estándar: {std.item()}')

Media: 0.5272899866104126
Desviación estándar: 0.29671019315719604


##### **3.c. Multiplicación elemento a elemento**

In [20]:
y1 = tensor * tensor
y2 = tensor.mul(tensor)

print(y1)
print(y2)

tensor([[0.0222, 0.2367, 0.9715, 0.0284],
        [0.3410, 0.4811, 0.3400, 0.0165],
        [0.3273, 0.8553, 0.0725, 0.6122]], device='cuda:0')
tensor([[0.0222, 0.2367, 0.9715, 0.0284],
        [0.3410, 0.4811, 0.3400, 0.0165],
        [0.3273, 0.8553, 0.0725, 0.6122]], device='cuda:0')


##### **3.d. Multiplicación de matrices de tensores**

In [21]:
z1 = tensor @ tensor.T
z2 = tensor.matmul(tensor.T)

print(z1)
print(z2)

tensor([[1.2588, 1.0209, 0.9325],
        [1.0209, 1.1786, 1.2331],
        [0.9325, 1.2331, 1.8674]], device='cuda:0')
tensor([[1.2588, 1.0209, 0.9325],
        [1.0209, 1.1786, 1.2331],
        [0.9325, 1.2331, 1.8674]], device='cuda:0')


### **4. *Broadcasting* y operaciones de reducción**

##### **4.a. Broadcasting**

In [22]:
# Broadcasting.
A = torch.tensor([[1.0], [2.0], [3.0], [4.0], [5.0]])
B = torch.tensor([[10.0, 20.0, 30.0, 40.0, 50.0]])

result = A + B

print(f'Tensor A:\n{A}')
print(f'\nTensor B:\n{B}')
print(f'\nSuma elemento a elemento:\n{result}')


Tensor A:
tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.]])

Tensor B:
tensor([[10., 20., 30., 40., 50.]])

Suma elemento a elemento:
tensor([[11., 21., 31., 41., 51.],
        [12., 22., 32., 42., 52.],
        [13., 23., 33., 43., 53.],
        [14., 24., 34., 44., 54.],
        [15., 25., 35., 45., 55.]])


##### **4.b. Operaciones de reducción**

In [23]:
tensor = torch.tensor([[14, 11, 13, 21, 32],
                       [1, 2, 3, 4, 5],
                       [1., 1., 1., 1., 1.]])

sum_along_dim0 = torch.sum(tensor, dim = 0)
mean_along_dim1 = torch.mean(tensor, dim = 1)
max_value = torch.max(tensor)

print(tensor)
print(f'\nSumar sobre la dimensión 0: {sum_along_dim0}')
print(f'\nMedia de los valores de la dimensión 1: {mean_along_dim1}')
print(f'\nMáximo valor del tensor: {max_value.item()}')


tensor([[14., 11., 13., 21., 32.],
        [ 1.,  2.,  3.,  4.,  5.],
        [ 1.,  1.,  1.,  1.,  1.]])

Sumar sobre la dimensión 0: tensor([16., 14., 17., 26., 38.])

Media de los valores de la dimensión 1: tensor([18.2000,  3.0000,  1.0000])

Máximo valor del tensor: 32.0


### **5. *Indexing* y *reshaping***


##### **5.a. Indexing**

In [24]:
tensor = torch.rand(4, 4)
print(f'{tensor}')
print(f'\nPrimera fila: {tensor[0]}')
print(f'\nPrimera columna: {tensor[:, 0]}')
print(f'\nÚltima columna: {tensor[..., -1]}')

# Cambiamos la segunda columna.
tensor[:, 1] = 0
print(f'\nHabiendo modificado la segunda columna:\n{tensor}')

tensor([[0.2719, 0.4632, 0.7671, 0.5024],
        [0.1025, 0.7600, 0.8035, 0.7653],
        [0.8709, 0.7231, 0.8364, 0.5820],
        [0.8395, 0.0595, 0.4315, 0.4425]])

Primera fila: tensor([0.2719, 0.4632, 0.7671, 0.5024])

Primera columna: tensor([0.2719, 0.1025, 0.8709, 0.8395])

Última columna: tensor([0.5024, 0.7653, 0.5820, 0.4425])

Habiendo modificado la segunda columna:
tensor([[0.2719, 0.0000, 0.7671, 0.5024],
        [0.1025, 0.0000, 0.8035, 0.7653],
        [0.8709, 0.0000, 0.8364, 0.5820],
        [0.8395, 0.0000, 0.4315, 0.4425]])


##### **5.b. [*Reshape*](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html)**

In [33]:
tensor_a = torch.rand(10, 2)

# Convertir a dimensión (5, 4).
tensor_b = tensor_a.view(5, 4)

# Convertir a dimensión (2, 10).
tensor_c = tensor_a.view(2, 10) #(-1,10)

print(f'Tensor original con dimensión (10, 2):\n{tensor_a}')
print(f'\nTensor modificado a dimensión (5, 4):\n{tensor_b}')
print(f'\nTensor modificado a dimensión (2, 10):\n{tensor_c}')

Tensor original con dimensión (10, 2):
tensor([[0.5252, 0.4526],
        [0.1176, 0.1741],
        [0.6308, 0.4461],
        [0.4822, 0.5782],
        [0.6252, 0.2436],
        [0.3430, 0.1256],
        [0.4559, 0.4430],
        [0.8089, 0.6360],
        [0.3043, 0.8103],
        [0.3542, 0.4307]])

Tensor modificado a dimensión (5, 4):
tensor([[0.5252, 0.4526, 0.1176, 0.1741],
        [0.6308, 0.4461, 0.4822, 0.5782],
        [0.6252, 0.2436, 0.3430, 0.1256],
        [0.4559, 0.4430, 0.8089, 0.6360],
        [0.3043, 0.8103, 0.3542, 0.4307]])

Tensor modificado a dimensión (2, 10):
tensor([[0.5252, 0.4526, 0.1176, 0.1741, 0.6308, 0.4461, 0.4822, 0.5782, 0.6252,
         0.2436],
        [0.3430, 0.1256, 0.4559, 0.4430, 0.8089, 0.6360, 0.3043, 0.8103, 0.3542,
         0.4307]])


### **6. Concatenar y apilar**

In [34]:
tensor1 = torch.rand(3, 3)
tensor2 = torch.rand(3, 3)
tensor3 = torch.rand(3, 3)

print(f'Tensor 1:\n{tensor1}')
print(f'Tensor 2:\n{tensor2}')
print(f'Tensor 3:\n{tensor3}')

Tensor 1:
tensor([[0.1845, 0.7950, 0.4021],
        [0.7841, 0.0507, 0.9523],
        [0.9379, 0.1165, 0.9906]])
Tensor 2:
tensor([[0.7561, 0.5811, 0.7827],
        [0.3359, 0.8316, 0.0576],
        [0.0252, 0.9417, 0.1110]])
Tensor 3:
tensor([[0.1175, 0.6041, 0.5114],
        [0.7200, 0.3670, 0.8785],
        [0.6257, 0.5348, 0.2471]])


In [40]:
# Concatenamos sobre la primera dimensión (la número 0).
concatenated_tensor = torch.cat((tensor1, tensor2, tensor3), dim = 0)

print(concatenated_tensor)
print(concatenated_tensor.shape)

tensor([[0.1845, 0.7950, 0.4021],
        [0.7841, 0.0507, 0.9523],
        [0.9379, 0.1165, 0.9906],
        [0.7561, 0.5811, 0.7827],
        [0.3359, 0.8316, 0.0576],
        [0.0252, 0.9417, 0.1110],
        [0.1175, 0.6041, 0.5114],
        [0.7200, 0.3670, 0.8785],
        [0.6257, 0.5348, 0.2471]])
torch.Size([9, 3])


In [38]:
# Apilamos sobre la dimension 0.
stacked_tensor = torch.stack((tensor1, tensor2, tensor3), dim = 0)

print(stacked_tensor)
print(stacked_tensor.shape)

tensor([[[0.1845, 0.7950, 0.4021],
         [0.7841, 0.0507, 0.9523],
         [0.9379, 0.1165, 0.9906]],

        [[0.7561, 0.5811, 0.7827],
         [0.3359, 0.8316, 0.0576],
         [0.0252, 0.9417, 0.1110]],

        [[0.1175, 0.6041, 0.5114],
         [0.7200, 0.3670, 0.8785],
         [0.6257, 0.5348, 0.2471]]])
torch.Size([3, 3, 3])


### **7. Conversion entre PyTorch y NumPy**

In [41]:
pytorch_tensor = torch.rand(2, 3)
numpy_array = np.ones((2, 3))

# Convertimos un tensor de PyTorch a una matriz de NumPy.
converted_to_numpy = pytorch_tensor.numpy()
print(f'{converted_to_numpy} es de tipo {type(converted_to_numpy)}')

# Convertimos una matriz de NumPy a un tensor de PyTorch.
converted_to_pytorch = torch.from_numpy(numpy_array)
print(f'\n{converted_to_pytorch} es de tipo {type(converted_to_pytorch)}')

[[0.9695735  0.36893946 0.5095269 ]
 [0.22743559 0.41575086 0.8659818 ]] es de tipo <class 'numpy.ndarray'>

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64) es de tipo <class 'torch.Tensor'>


Es importante saber que estos objetos convertidos están utilizando la **misma memoria** subyacente que sus objetos fuente, lo que significa que los cambios en uno se reflejan en el otro. Veamos un ejemplo.

In [42]:
numpy_array[1, 1] = 23
print(converted_to_pytorch)

pytorch_tensor[1, 1] = 17
print(f'\n{converted_to_numpy}')

tensor([[ 1.,  1.,  1.],
        [ 1., 23.,  1.]], dtype=torch.float64)

[[ 0.9695735   0.36893946  0.5095269 ]
 [ 0.22743559 17.          0.8659818 ]]
