Universidad Torcuato Di Tella

Licenciatura en Tecnología Digital\
**Tecnología Digital VI: Inteligencia Artificial**

# **Tensores de PyTorch**

Esta *notebook* tiene como objetivo brindar una **comprensión** fundamental de los **tensores** y explorar sus **operaciones** esenciales.

Pueden encontrar la documentación oficial [acá](https://pytorch.org/docs/stable/torch.html).

In [2]:
import torch

### **1. Creación de tensores**


In [3]:
# Tensor vacío.
shape = (2, 3)
empty_torch = torch.empty(shape)
print(f'Tensor vacío:\n{empty_torch}')

# Tensor con ceros.
zeros = torch.zeros(shape)
print(f'\nTensor con ceros:\n{zeros}')

# Tensor con unos.
ones = torch.ones(shape)
print(f'\nTensor con unos:\n{ones}')

# Tensor con valores aleatorios.
torch.manual_seed(11)
random = torch.rand(shape)
print(f'\nTensor con valores aleatorios:\n{random}')


Tensor vacío:
tensor([[0., 0., 0.],
        [0., 0., 0.]])

Tensor con ceros:
tensor([[0., 0., 0.],
        [0., 0., 0.]])

Tensor con unos:
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Tensor con valores aleatorios:
tensor([[0.1490, 0.4866, 0.9857],
        [0.1684, 0.5839, 0.6936]])


In [5]:
import numpy as np

# Tensores a partir de datos.
data = [[3.1415926, 2.71828], [1.61803, 0.0072897]]
tensor_data = torch.tensor(data)
print(f'Tensor a partir de {type(data)} queda:\n{tensor_data}')

# Tensor a partir de array.
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(f'\nTensor a partir de {type(np_array)} queda:\n{x_np}')

# Tensor a partir de otro tensor (toma las dimensiones del tensor para crear uno nuevo).
x_ones = torch.ones_like(tensor_data)
print(f'\nTensor a partir de {type(tensor_data)} queda:\n{x_ones}')

Tensor a partir de <class 'list'> queda:
tensor([[3.1416, 2.7183],
        [1.6180, 0.0073]])

Tensor a partir de <class 'numpy.ndarray'> queda:
tensor([[3.1416, 2.7183],
        [1.6180, 0.0073]], dtype=torch.float64)

Tensor a partir de <class 'torch.Tensor'> queda:
tensor([[1., 1.],
        [1., 1.]])


### **2. Atributos de un tensor**

In [6]:
torch.manual_seed(11)
tensor = torch.rand(3, 4)

print(f'Dimensiones: {tensor.shape}')
print(f'Tipo de dato: {tensor.dtype}')
print(f'Dispositivo en el cual está almacenado: {tensor.device}')

Dimensiones: torch.Size([3, 4])
Tipo de dato: torch.float32
Dispositivo en el cual está almacenado: cpu


### **3. Operaciones con tensores**


In [7]:
print(tensor)

tensor([[0.1490, 0.4866, 0.9857, 0.1684],
        [0.5839, 0.6936, 0.5831, 0.1284],
        [0.5721, 0.9248, 0.2693, 0.7825]])


##### **3.a. Sumar todos los elementos**

In [8]:
sum = torch.sum(tensor)
print(f'Suma de todos los elementos: {sum.item()}')

Suma de todos los elementos: 6.327479362487793


##### **3.b. Media y desviación estándar**

In [9]:
mean = torch.mean(tensor)
std  = torch.std(tensor)
print(f'Media: {mean.item()}')
print(f'Desviación estándar: {std.item()}')

Media: 0.5272899270057678
Desviación estándar: 0.29671019315719604


##### **3.c. Multiplicación elemento a elemento**

In [10]:
y1 = tensor * tensor
y2 = tensor.mul(tensor)

print(y1)
print(y2)

tensor([[0.0222, 0.2367, 0.9715, 0.0284],
        [0.3410, 0.4811, 0.3400, 0.0165],
        [0.3273, 0.8553, 0.0725, 0.6122]])
tensor([[0.0222, 0.2367, 0.9715, 0.0284],
        [0.3410, 0.4811, 0.3400, 0.0165],
        [0.3273, 0.8553, 0.0725, 0.6122]])


##### **3.d. Multiplicación de matrices de tensores**

In [11]:
z1 = tensor @ tensor.T
z2 = tensor.matmul(tensor.T)

print(z1)
print(z2)

tensor([[1.2588, 1.0209, 0.9325],
        [1.0209, 1.1786, 1.2331],
        [0.9325, 1.2331, 1.8674]])
tensor([[1.2588, 1.0209, 0.9325],
        [1.0209, 1.1786, 1.2331],
        [0.9325, 1.2331, 1.8674]])


### **4. *Broadcasting* y operaciones de reducción**

##### **4.a. Broadcasting**

In [12]:
# Broadcasting.
A = torch.tensor([[1.0], [2.0], [3.0], [4.0], [5.0]])
B = torch.tensor([[10.0, 20.0, 30.0, 40.0, 50.0]])

result = A + B

print(f'Tensor A:\n{A}')
print(f'\nTensor B:\n{B}')
print(f'\nSuma elemento a elemento:\n{result}')


Tensor A:
tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.]])

Tensor B:
tensor([[10., 20., 30., 40., 50.]])

Suma elemento a elemento:
tensor([[11., 21., 31., 41., 51.],
        [12., 22., 32., 42., 52.],
        [13., 23., 33., 43., 53.],
        [14., 24., 34., 44., 54.],
        [15., 25., 35., 45., 55.]])


##### **4.b. Operaciones de reducción**

In [14]:
tensor = torch.tensor([[14, 11, 13, 21, 32],
                       [1, 2, 3, 4, 5],
                       [1., 1., 1., 1., 1.]])

sum_along_dim0 = torch.sum(tensor, dim = 0)
mean_along_dim1 = torch.mean(tensor, dim = 1)
max_value = torch.max(tensor)

print(tensor)
print(f'\nSumar sobre la dimensión 0: {sum_along_dim0}')
print(f'\nMedia de los valores de la dimensión 1: {mean_along_dim1}')
print(f'\nMáximo valor del tensor: {max_value.item()}')


tensor([[14., 11., 13., 21., 32.],
        [ 1.,  2.,  3.,  4.,  5.],
        [ 1.,  1.,  1.,  1.,  1.]])

Sumar sobre la dimensión 0: tensor([16., 14., 17., 26., 38.])

Media de los valores de la dimensión 1: tensor([18.2000,  3.0000,  1.0000])

Máximo valor del tensor: 32.0


### **5. *Indexing* y *reshaping***


##### **5.a. Indexing**

In [16]:
tensor = torch.rand(4, 4)
print(f'{tensor}')
print(f'\nPrimera fila: {tensor[0]}')
print(f'\nPrimera columna: {tensor[:, 0]}')
print(f'\nÚltima columna: {tensor[..., -1]}')

# Cambiamos la segunda columna.
tensor[:, 1] = 0
print(f'\nHabiendo modificado la segunda columna:\n{tensor}')

tensor([[0.2622, 0.6301, 0.8775, 0.1626],
        [0.2438, 0.3382, 0.8847, 0.0763],
        [0.9900, 0.1944, 0.4256, 0.4382],
        [0.2988, 0.8474, 0.4785, 0.1935]])

Primera fila: tensor([0.2622, 0.6301, 0.8775, 0.1626])

Primera columna: tensor([0.2622, 0.2438, 0.9900, 0.2988])

Última columna: tensor([0.1626, 0.0763, 0.4382, 0.1935])

Habiendo modificado la segunda columna:
tensor([[0.2622, 0.0000, 0.8775, 0.1626],
        [0.2438, 0.0000, 0.8847, 0.0763],
        [0.9900, 0.0000, 0.4256, 0.4382],
        [0.2988, 0.0000, 0.4785, 0.1935]])


##### **5.b. [*Reshape*](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html)**

In [17]:
tensor_a = torch.rand(10, 2)

# Convertir a dimensión (5, 4).
tensor_b = tensor_a.view(5, 4)

# Convertir a dimensión (2, 10).
tensor_c = tensor_a.view(2, 10)

print(f'Tensor original con dimensión (10, 2):\n{tensor_a}')
print(f'\nTensor modificado a dimensión (5, 4):\n{tensor_b}')
print(f'\nTensor modificado a dimensión (2, 10):\n{tensor_c}')

Tensor original con dimensión (10, 2):
tensor([[0.2239, 0.5639],
        [0.6125, 0.2264],
        [0.5853, 0.1851],
        [0.4920, 0.7171],
        [0.4578, 0.3566],
        [0.4831, 0.6752],
        [0.2525, 0.5272],
        [0.8281, 0.4956],
        [0.8292, 0.0482],
        [0.0826, 0.2730]])

Tensor modificado a dimensión (5, 4):
tensor([[0.2239, 0.5639, 0.6125, 0.2264],
        [0.5853, 0.1851, 0.4920, 0.7171],
        [0.4578, 0.3566, 0.4831, 0.6752],
        [0.2525, 0.5272, 0.8281, 0.4956],
        [0.8292, 0.0482, 0.0826, 0.2730]])

Tensor modificado a dimensión (2, 10):
tensor([[0.2239, 0.5639, 0.6125, 0.2264, 0.5853, 0.1851, 0.4920, 0.7171, 0.4578,
         0.3566],
        [0.4831, 0.6752, 0.2525, 0.5272, 0.8281, 0.4956, 0.8292, 0.0482, 0.0826,
         0.2730]])


### **6. Concatenar y apilar**

In [18]:
tensor1 = torch.rand(3, 3)
tensor2 = torch.rand(3, 3)
tensor3 = torch.rand(3, 3)

print(f'Tensor 1:\n{tensor1}')
print(f'Tensor 2:\n{tensor2}')
print(f'Tensor 3:\n{tensor3}')

Tensor 1:
tensor([[0.7694, 0.8017, 0.1284],
        [0.6878, 0.4103, 0.6449],
        [0.9702, 0.0159, 0.5884]])
Tensor 2:
tensor([[0.8002, 0.5418, 0.2007],
        [0.4079, 0.3510, 0.8876],
        [0.9466, 0.3037, 0.0089]])
Tensor 3:
tensor([[0.3416, 0.2241, 0.9258],
        [0.9720, 0.7581, 0.4573],
        [0.0179, 0.5359, 0.3075]])


In [19]:
# Concatenamos sobre la primera dimensión (la número 0).
concatenated_tensor = torch.cat((tensor1, tensor2, tensor3), dim = 0)

print(concatenated_tensor)
print(concatenated_tensor.shape)

tensor([[0.7694, 0.8017, 0.1284],
        [0.6878, 0.4103, 0.6449],
        [0.9702, 0.0159, 0.5884],
        [0.8002, 0.5418, 0.2007],
        [0.4079, 0.3510, 0.8876],
        [0.9466, 0.3037, 0.0089],
        [0.3416, 0.2241, 0.9258],
        [0.9720, 0.7581, 0.4573],
        [0.0179, 0.5359, 0.3075]])
torch.Size([9, 3])


In [20]:
# Apilamos sobre la dimension 0.
stacked_tensor = torch.stack((tensor1, tensor2, tensor3), dim = 0)

print(stacked_tensor)
print(stacked_tensor.shape)

tensor([[[0.7694, 0.8017, 0.1284],
         [0.6878, 0.4103, 0.6449],
         [0.9702, 0.0159, 0.5884]],

        [[0.8002, 0.5418, 0.2007],
         [0.4079, 0.3510, 0.8876],
         [0.9466, 0.3037, 0.0089]],

        [[0.3416, 0.2241, 0.9258],
         [0.9720, 0.7581, 0.4573],
         [0.0179, 0.5359, 0.3075]]])
torch.Size([3, 3, 3])


### **7. Conversion entre PyTorch y NumPy**

In [21]:
pytorch_tensor = torch.rand(2, 3)
numpy_array = np.ones((2, 3))

# Convertimos un tensor de PyTorch a una matriz de NumPy.
converted_to_numpy = pytorch_tensor.numpy()
print(f'{converted_to_numpy} es de tipo {type(converted_to_numpy)}')

# Convertimos una matriz de NumPy a un tensor de PyTorch.
converted_to_pytorch = torch.from_numpy(numpy_array)
print(f'\n{converted_to_pytorch} es de tipo {type(converted_to_pytorch)}')

[[0.5055624  0.2658872  0.44788253]
 [0.78248024 0.9937389  0.91107416]] es de tipo <class 'numpy.ndarray'>

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64) es de tipo <class 'torch.Tensor'>


Es importante saber que estos objetos convertidos están utilizando la **misma memoria** subyacente que sus objetos fuente, lo que significa que los cambios en uno se reflejan en el otro. Veamos un ejemplo.

In [22]:
numpy_array[1, 1] = 23
print(converted_to_pytorch)

pytorch_tensor[1, 1] = 17
print(f'\n{converted_to_numpy}')

tensor([[ 1.,  1.,  1.],
        [ 1., 23.,  1.]], dtype=torch.float64)

[[ 0.5055624   0.2658872   0.44788253]
 [ 0.78248024 17.          0.91107416]]
